### PR TITLE
Patch 1

### PR DESCRIPTION
**Pull request by rajatmo**

### CODE REVIEW

**Comment by qgp** [comment]
Could you please provide a reasonable explanation? No idea what "Patch 1" is supposed to be ...

**Comment by rajatmo** [comment]
I updated the readme file. The frameworks aren’t accessible if I don’t build it with the option -DCMAKE_MACOSX_RPATH=ON on macOS. As for the name ‘patch 1’, it’s an unfortunate choice, I see. And the name was given automatically when I tried to edit the readme file. It’s not a patch of the actual libraries, just an update on the instructions of how to install it in macOS. 

Thank you,
Rajat Kumar Mandal

**Comment by ktf** [comment]
Dear @rajatmo, I am not sure this is actually needed, since we rewrite everything with `install_name_tool` after the build. I also see you seems to have some CMS connection, is that right? If yes, you are contributing to an ALICE repository, is this really what you meant to do?

**Comment by rajatmo** [comment]
> you seems to have some CMS connection, is that right? 

yes.

> you are contributing to an ALICE repository, is this really what you meant to do?

Not really, I only use hepmc2 as a plugin in Pythia8 in my own system, I don't really mean to contribute to the hempc repo. As I said, there's just a problem in the installation/linking phase. 


For completeness, if I follow the exact outlines, the cmake command gives a warning:

```
 CMake Warning (dev):
  Policy CMP0042 is not set: MACOSX_RPATH is enabled by default.  Run "cmake
  --help-policy CMP0042" for policy details.  Use the cmake_policy command to
  set the policy and suppress this warning.

  MACOSX_RPATH is not specified for the following targets:

   HepMC
   HepMCfio

```
Also, if I ignore the warning and go on anyway, then Pythia8's say, example/main41.cc gives an error runtime:

```
Rajats-MacBook-Pro:examples rajat$ make main41
g++ main41.cc -o main41 -I/Users/rajat/test1/include -I../include -O2  -pedantic -W -Wall -Wshadow -fPIC -L../lib -Wl,-rpath,../lib -lpythia8 -ldl \
	 -L/Users/rajat/test1/lib -Wl,-rpath,/Users/rajat/test1/lib -lHepMC
Rajats-MacBook-Pro:examples rajat$ ./main41 
dyld: Library not loaded: libHepMC.4.dylib
  Referenced from: /Users/rajat/pythia8230/examples/./main41
  Reason: image not found
Abort trap: 6

```

These go away if I just set -DCMAKE_MACOSX_RPATH=ON in the make command.

**Comment by ktf** [comment]
I think you should be contributing your fix to the upstream repository:

https://gitlab.cern.ch/hepmc/

We tend to put here only patches that are required by ALICE production and which are not yet available from upstream. Everything else should go in the official HEPMC repository.

**Comment by rajatmo** [comment]
I see, I'm extremely sorry, I didn't know the purpose of this repo. Please don't mind.

**Comment by ktf** [comment]
No worries and thank you for your attempt.

**Pull request closed without merging**
